# Redirect robots.txt based on context
[[redirects]]
  from = "/robots.txt"
  to = "/robots-production.txt"
  status = 200
  force = true
  conditions = { Context = "production" }

[[redirects]]
  from = "/robots.txt"
  to = "/robots-development.txt"
  status = 200
  force = true
  conditions = { Context = "deploy-preview" }

[[redirects]]
  from = "/robots.txt"
  to = "/robots-development.txt"
  status = 200
  force = true
  conditions = { Context = "branch-deploy" }

[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/checkBilling"
  to = "/.netlify/functions/checkBilling"
  status = 200

# Redirect from old domain to new domain while old domain is being taken down
[[redirects]]
  from = "https://fastandeasysolar.com/*"
  to = "https://apexsolarsolution.net/:splat"
  status = 301
  force = true