# Redirect robots.txt based on context
[[redirects]]
  from = "/robots.txt"
  to = "/robots-production.txt"
  status = 200
  force = true
  conditions = { Context = "production" }

[[redirects]]
  from = "/robots.txt"
  to = "/robots-development.txt"
  status = 200
  force = true
  conditions = { Context = "deploy-preview" }

[[redirects]]
  from = "/robots.txt"
  to = "/robots-development.txt"
  status = 200
  force = true
  conditions = { Context = "branch-deploy" }

# Redirect the old domain to the new domain
[[redirects]]
  from = "https://fastandeasysolar.com/*"
  to = "https://fastandeasysolar.netlify.app/:splat"
  status = 301
  force = true